pm-backend/config/routes.rb
Rails.application.routes.draw do
  root "park_spaces#index"
  devise_for :users


  resources :park_spaces do
    resources :park_vehicles
  end

  namespace :api do
    namespace :v1 do
      resources :park_spaces
      get "park_spaces/:location", to: "park_spaces#park_space"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

pm-backend/app/models/park_space.rb
class ParkSpace < ApplicationRecord
  validates :latitude, presence: true
  validates :longitude, presence: true

  belongs_to :user
  has_many :park_vehicles, dependent: :destroy
  
  has_many :vehicles, dependent: :destroy
  accepts_nested_attributes_for :vehicles, allow_destroy: true

   # Add geocoding functionality to ParkSpace model
   geocoded_by :location
   after_validation :geocode, if: :will_save_change_to_location?

   def distance_from(latitude, longitude)
    Haversine.distance(latitude, longitude, self.latitude, self.longitude).to_km
  end
end

pm-backend/app/controllers/api/v1/park_spaces_controller.rb
# class Api::V1::ParkSpacesController < ApplicationController
#   def park_space
#     location = params[:location]
#     if location.blank?
#       render json: { error: "Location parameter is required" }, status: :bad_request
#       return
#     end

#     # Geocode the location to get latitude and longitude
#     results = Geocoder.search(location)

#     if results.empty?
#       render json: { error: "Geocoder not searching! Location not found" }, status: :not_found
#       return
#     end

#     coordinates = results.first.coordinates # [latitude, longitude]
#     latitude, longitude = coordinates

#     # Find nearby park spaces
#     park_spaces = ParkSpace.near([ latitude, longitude ], 10, units: :km).includes(:vehicles) # 10 km radius

#     # Render the park spaces with associated vehicles
#     # render json: park_spaces.as_json(include: { vehicles: { except: :id } }, except: :id)
#     render json: park_spaces.to_json(include: :vehicles)
#   end
# end

# app/controllers/api/v1/park_spaces_controller.rb
class Api::V1::ParkSpacesController < ApplicationController
  before_action :authenticate_user!


  def index
    if ParkSpace.count.zero? 
      render json: {park_spaces: 0, message: 'No parking space created yet !'}, status: :ok
    else 
      render json: {park_spaces: ParkSpace.all }, status: :ok
    end
  end

  def new
    @park_space = ParkSpace.new
    @park_space.vehicles.build
    # 2.times { @park_space.vehicles.build }
  end

  def create
    @park_space = ParkSpace.new(park_space_params)
    @park_space.user = current_user
    # Geocode the location to get latitude and longitude if not supplied from form 
    if (!@park_space.latitude && !@park_space.longitude) 
      geocode_location(@park_space)
    end

    if @park_space.save
      render json: {message: 'Park space was successfully created.', park_space: @park_space}, status: :created
    else
      render json: {message: 'Failed to create park space.', errors: @park_space.errors.full_messages.join(',')}, status: :unprocessable_entity
    end
  end

  def edit 
    @park_space = ParkSpace.find(params[:id])  
  end

  def update 
    @park_space = ParkSpace.find(params[:id])
    if @park_space.update(park_space_params)
      render json: {message: 'Park space was successfully updated.', park_space: @park_space}, status: :ok
    else 
      render json: {message: 'Failed to create park space.', errors: @park_space.errors.full_messages.join(',')}, status: :unprocessable_entity
    end
  end


  def park_space
    location = params[:location]
    if location.blank?
      render json: { error: "Location parameter is required" }, status: :bad_request
      return
    end

    # Geocode the location to get latitude and longitude
    results = fetch_coordinates(location)
    if results.empty?
      render json: { error: "Location not found" }, status: :not_found
      return
    end

    coordinates = results.first
    latitude, longitude = coordinates
    latitude, longitude = [ 27.6758786, 85.3854371 ] if coordinates.blank?

    # Find nearby park spaces
    park_spaces = ParkSpace.all.select do |park_space|
      next if park_space.latitude.nil? || park_space.longitude.nil?

      distance = Haversine.distance(latitude, longitude, park_space.latitude, park_space.longitude).to_km
      distance <= 10 # 10 km radius
    end.compact

    render json: park_spaces.to_json(include: :vehicles)
  end

  private

  def fetch_coordinates(location)
    # Example static lookup
    locations = {
      "balkumari" => [ 27.671189199022322, 85.33709456556089 ]
      # Add more locations here
    }
    [ locations[location] || [] ]
  end


  def park_space_params
    params.require(:park_space).permit(:name, :location, :latitude, :longitude,  :user_id,
                                       vehicles_attributes: [ :id, :vehicle_name, :capacity, :hourly_rate, :status, :_destroy ])
  end

  def geocode_location(park_space)
    results = Geocoder.search(park_space.location)
    if results.any?
      coordinates = results.first.coordinates
      park_space.latitude = coordinates[0]
      park_space.longitude = coordinates[1]
    else
      # Handle cases where location cannot be geocoded, e.g., set defaults or raise an error
      park_space.latitude = 26.6686775
      park_space.longitude = 87.6767778
    end
  end

end

pm-backend/app/controllers/park_spaces_controller.rb
class ParkSpacesController < ApplicationController
  before_action :authenticate_user!

  def index
    @park_spaces = ParkSpace.all
  end

  def new
    @park_space = ParkSpace.new
    @park_space.vehicles.build
    # 2.times { @park_space.vehicles.build }
  end

  def create
    @park_space = ParkSpace.new(park_space_params)
    @park_space.user = current_user
    # Geocode the location to get latitude and longitude if not supplied from form 
    if (!@park_space.latitude && !@park_space.longitude) 
      geocode_location(@park_space)
    end

    if @park_space.save
      redirect_to park_spaces_path,  notice: "Park space was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @park_space = ParkSpace.find(params[:id])  
  end

  def update 
    @park_space = ParkSpace.find(params[:id])
    if @park_space.update(park_space_params)
      # redirect_to park_space_path(@park_space)
      redirect_to park_spaces_path, notice: "Park space updated !"
    else 
      render :edit, status: :unprocessable_entity, notice: 'Unable to update park space'
    end
  end




  private
  def park_space_params
    params.require(:park_space).permit(:name, :location, :latitude, :longitude,  :user_id,
                                       vehicles_attributes: [ :id, :vehicle_name, :capacity, :hourly_rate, :status, :_destroy ])
  end

  def geocode_location(park_space)
    results = Geocoder.search(park_space.location)
    if results.any?
      coordinates = results.first.coordinates
      park_space.latitude = coordinates[0]
      park_space.longitude = coordinates[1]
    else
      # Handle cases where location cannot be geocoded, e.g., set defaults or raise an error
      park_space.latitude = 26.6686775
      park_space.longitude = 87.6767778
    end
  end
end

pm-backend/app/helpers/api/v1/park_spaces_helper.rb
module Api::V1::ParkSpacesHelper
end

pm-backend/app/helpers/park_spaces_helper.rb
module ParkSpacesHelper
end

pm-backend/app/views/park_spaces/_vehicle_fields.html.erb
<div class="nested-fields">
  <div class="card mb-3">
    <div class="card-body">
      <div class="mb-3">
        <%= f.label :vehicle_name, class: 'form-label' %>
        <%= f.select :vehicle_name, Vehicle.vehicle_names.keys.map { |v| [v.humanize, v] }, {}, class: 'form-select' %>
      </div>
      <div class="mb-3">
        <%= f.label :capacity, class: 'form-label' %>
        <%= f.number_field :capacity, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :hourly_rate, class: 'form-label' %>
        <%= f.number_field :hourly_rate, class: 'form-control' %>
      </div>

      <div class="d-flex justify-content-between">
        <div class="mb-3">
          <%= f.label :status, class: 'form-label' %>
          <%= f.check_box :status, class: 'form-check-input' %>
        </div>

        <%# Using JavaScript to remove for interactivity  %>
        <div class="mb-3">
          <%= f.hidden_field :_destroy %>
          <%= link_to 'Remove', '#', class: 'btn btn-danger remove-fields' %>
        </div>
      </div>

      <%# Withou JavaScript to remove %>
      <%#= f.label :_destroy, 'Remove Vehicle'%>
      <%#= f.check_box :_destroy%>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
      // Handle dynamic field removal.
      document.body.addEventListener('click', function(event) {
        if (event.target.classList.contains('remove-fields')) {
          event.preventDefault();

          // Find the parent element to remove
          const nestedFields = event.target.closest('.nested-fields');

          if (nestedFields) {
            // Mark the hidden _destroy field as true
            nestedFields.querySelector('input[type="hidden"]').value = '1';
            // Hide the nested fields (you can also remove it from DOM if needed)
            nestedFields.style.display = 'none';
          }
        }
      });
    });
</script>

pm-backend/app/views/park_spaces/edit.html.erb
<h1>Edit Park Space</h1>

<%= form_with(model: @park_space, local: true) do |form| %>
  <% if @park_space.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@park_space.errors.count, "error") %> prohibited this park space from being saved:</h4>
      <ul>
        <% @park_space.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class: 'form-label' %>
    <%= form.text_field :location, class: 'form-control', required: true %>
  </div>

  <div class="d-flex w-full">
    <div class="mb-3 me-3 flex-fill">
      <%= form.label :latitude, class: 'form-label' %>
      <%= form.number_field :latitude, class: 'form-control', step: 0.0000001 %>
    </div>
    <div class="mb-3 flex-fill">
      <%= form.label :longitude, class: 'form-label' %>
      <%= form.number_field :longitude, class: 'form-control',  step: 0.0000001 %>
    </div>
  </div>

  <h2>Vehicles</h2>
  <div class="field_wrapper">
    <%= form.fields_for :vehicles do |vehicle_form| %>
      <%= render 'vehicle_fields', f: vehicle_form %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Update Park Space', class: 'btn btn-primary' %>
    <%= link_to 'Back', park_spaces_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

pm-backend/app/views/park_spaces/index.html.erb
<h1>Park Spaces</h1>

<%= link_to 'New Park Space', new_park_space_path, class: 'btn btn-primary mb-3' %>

<% @park_spaces.each do |park_space| %>
  <h1><%= park_space.name %> </h1>
  <p><%= park_space.location%></p>
  <%= link_to 'Add Park Vechile', new_park_space_park_vehicle_path(park_space), class: 'btn btn-info btn-sm' %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Vehicle</th>
        <th>Capacity</th>
        <th>Hourly Rate</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% park_space.vehicles.each do |vehicle| %>
        <tr>
          <td><%= vehicle.vehicle_name.humanize %></td>
          <td><%= vehicle.capacity %></td>
          <td><%= vehicle.hourly_rate %></td>
          <td><%= vehicle.status ? 'Available' : 'Pack' %></td>
          <td>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Edit', edit_park_space_path(park_space), class: 'btn btn-warning btn-sm' %>
  <%= link_to 'Delete', park_space_path(park_space), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

<% end %>

pm-backend/app/views/park_spaces/new.html.erb
<h1>New Park Space</h1>

<%= form_with(model: @park_space, local: true) do |form| %>
  <% if @park_space.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@park_space.errors.count, "error") %> prohibited this park space from being saved:</h4>
      <ul>
        <% @park_space.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class: 'form-label' %>
    <%= form.text_field :location, class: 'form-control', required: true %>
  </div>

  <div class="d-flex w-full">
    <div class="mb-3 me-3 flex-fill">
      <%= form.label :latitude, class: 'form-label' %>
      <%= form.number_field :latitude, class: 'form-control', step: 0.0000001 %>
    </div>
    <div class="mb-3 flex-fill">
      <%= form.label :longitude, class: 'form-label' %>
      <%= form.number_field :longitude, class: 'form-control',  step: 0.0000001 %>
    </div>
  </div>

  <h2>Vehicles</h2>
  <div class="field_wrapper">
    <%= form.fields_for :vehicles do |vehicle_form| %>
      <%= render 'vehicle_fields', f: vehicle_form %>
    <% end %>
  </div>

  <%= link_to_add_fields "Add Vehicles", form, :vehicles%>

  <div class="mb-3">
    <%= form.submit 'Create Park Space', class: 'btn btn-primary' %>
    <%= link_to 'Back', park_spaces_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    // Attach event listener to the whole document
    document.body.addEventListener('click', function(event) {
      // Handle dynamic field addition
      if (event.target && event.target.classList.contains('add_fields')) {
        event.preventDefault();

        console.log("Add vehicle clicked !!")

        // Extract data attributes from the clicked element
        const button = event.target;
        const time = new Date().getTime();
        const regexp = new RegExp(button.dataset.id, 'g');
        const fields = button.dataset.fields.replace(regexp, time);

        // Find the field wrapper and append the new fields
        const fieldWrapper = document.querySelector('.field_wrapper');
        if (fieldWrapper) {
          fieldWrapper.insertAdjacentHTML('beforeend', fields);
        }
      }
    });
  });
</script>